name: otree-env
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8=h99b78c6_7
  - ca-certificates=2024.9.24=hca03da5_0
  - icu=75.1=hfee45f7_0
  - krb5=1.21.3=hf3e1bf2_0
  - libcxx=14.0.6=h848a8c0_0
  - libedit=3.1.20230828=h80987f9_0
  - libffi=3.4.4=hca03da5_1
  - libpq=17.0=h7536039_1
  - libsqlite=3.45.2=h091b4b1_0
  - libzlib=1.3.1=h8359307_2
  - ncurses=6.4=h313beb8_0
  - openssl=3.4.0=h39f12f2_0
  - pip=24.2=py39hca03da5_0
  - psycopg2=2.9.9=py39hcc1965f_2
  - python=3.9.18=hd7ebdb9_1_cpython
  - python_abi=3.9=5_cp39
  - readline=8.2=h1a28f6b_0
  - setuptools=75.1.0=py39hca03da5_0
  - sqlite=3.45.2=hf2abe2d_0
  - tk=8.6.13=h5083fa2_1
  - tzdata=2024b=h04d1e81_0
  - wheel=0.44.0=py39hca03da5_0
  - xz=5.4.6=h80987f9_1
  - zlib=1.3.1=h8359307_2
  - pip:
      - aiofiles==0.6.0
      - click==7.1.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - fonttools==4.55.0
      - h11==0.14.0
      - importlib-resources==6.4.5
      - itsdangerous==1.1.0
      - kiwisolver==1.4.7
      - markupsafe==1.1.1
      - matplotlib==3.9.2
      - numpy==2.0.2
      - otree==5.6.0
      - packaging==24.2
      - pillow==11.0.0
      - pyparsing==3.2.0
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.5
      - six==1.16.0
      - sqlalchemy==1.3.22
      - starlette==0.14.1
      - uvicorn==0.13.4
      - websockets==8.1
      - wtforms==2.3.3
      - wtforms-sqlalchemy==0.2
      - zipp==3.21.0
prefix: /opt/anaconda3/envs/otree-env
